### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 02JanDal** [02JanDal/WonkoWeb#1]
* [ ] User authentication with external services (omniauth) (Github etc.) (#5)
    * https://github.com/MSch/devise-twitter
* [x] Sort out WUR/non-WUR
* [ ] Transfering, copying, etc. (#4)
* [ ] Commenting (mongoid-tree) (#6)
* [x] Feeds
* [ ] Notifications (#3)
* [x] User profiles
* [x] ERB -> Slim
* [ ] Voting/Rating/Liking/Following (#6)
